### ISSUE TITLE
Reverse Operation

### ISSUE THREAD

**Issue by HorizonsoftDaniel** [josh3ennett/excelFormulaUtilitiesJS#27]
Thanks for the great tool this has been super helpful, it would be really nice to have a tool to reverse the operation and turn it back into a single formula

Many thanks

**Comment by josh3ennett** [comment]
I added a "minify" option to the drop down, all it does is strip out white spaces.  Let me know what you think.

**Comment by HorizonsoftDaniel** [comment]
Perfect thanks! Added another issue btw! :)

**Comment by adamapple** [comment]
Just came across your project today, joshbtn, and it's pretty awesome. I love being able to much more easily reverse engineer formulas I built long ago and since forgotten how they work.

The only issue I see is that there is a problem with some of the spaces lingering during Minify. For example, let's say I take this formula and beautify it, it shows on multiple lines as intended.
`=vlookup([@[Time Needed]],Table9,2,FALSE)^(0-3)`

Beautified!
`=vlookup(`
`____[@[Time Needed]],`
`____Table9,`
`____2,`
`____FALSE  `
`) ^ ( 0 - 3 )`

Next, say I plop that into my text editor (Notepad++ is what I have), make a few tweaks, and copy-paste it back in to Minify, I get this:
`=vlookup( [@[Time Needed]], Table9, 2, FALSE ) ^ ( 0 - 3 )`
`---------^-----------------^-------^--^-----^-^-^-^-^-^-^`

Notice all the extra spaces as a result (indicated by the carets), which Excel yells at me about. Anything that can be done about that? For a formula this short, it's not a big deal - it's when they get to be really long that it's much harder to clean up. I thought about just using a Find & Replace to pull all the spaces, but often times column, table, or sheet names within a formula will have spaces and you wouldn't wanna mess those up.
